name: serendipiteur
favicon: null
layout_spectrum: 0.0012541841715574265
typography_spectrum: 0.021119587356224656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
